### ISSUE TITLE
Error at ./build.sh

### ISSUE THREAD

**Issue by Niellai** [PotatoSpudowski/fastLLaMa#18]
Any advice? what did i do wrong?
gcc --version

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Error message:
make[2]: *** [CMakeFiles/fastLlama.dir/build.make:76: CMakeFiles/fastLlama.dir/bridge.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/fastLlama.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
Unable to build bridge.cpp and link the 'libllama'

**Comment by imranraad07** [comment]
Share the full error message.

**Comment by Bigdimuss** [comment]
[ 50%] Building CXX object CMakeFiles/fastLlama.dir/bridge.cpp.o
/home/quentin/fastLLaMa/bridge.cpp:772:59: erreur: « optional » dans l'espace de noms « std » ne nomme pas un type de patron
  772 |     auto get_token_as_str(gpt_vocab::id id) const -> std::optional<std::string> {
      |                                                           ^~~~~~~~
/home/quentin/fastLLaMa/bridge.cpp:17:1: note: « std::optional » est défini dans l'en-tête « <optional> » ; avez-vous oublié « #include <optional> » ?
   16 | #include <pybind11/functional.h>
  +++ |+#include <optional>
   17 | 
/home/quentin/fastLLaMa/bridge.cpp:772:59: erreur: « ; » attendu à la fin de la déclaration du membre
  772 |     auto get_token_as_str(gpt_vocab::id id) const -> std::optional<std::string> {
      |                                                           ^~~~~~~~
      |                                                                   ;
/home/quentin/fastLLaMa/bridge.cpp:772:67: erreur: expected unqualified-id before « < » token
  772 | to get_token_as_str(gpt_vocab::id id) const -> std::optional<std::string> {
      |                                                             ^

/home/quentin/fastLLaMa/bridge.cpp: Dans la fonction membre « void FastLlamaBuffer<Fn>::flush_buffer() »:
/home/quentin/fastLLaMa/bridge.cpp:782:21: erreur: il n'y a pas d'argument pour « get_token_as_str » qui dépend d'un paramètre du patron, aussi une déclaration de « get_token_as_str » doit être disponible [-fpermissive]
  782 |         auto temp = get_token_as_str(id);
      |                     ^~~~~~~~~~~~~~~~
/home/quentin/fastLLaMa/bridge.cpp:782:21: note: (si vous utilisez « -fpermissive », G++ acceptera votre code, mais permettre l'utilisation d'un nom non déclaré est obsolète)
/home/quentin/fastLLaMa/bridge.cpp: Dans l'instanciation de « void FastLlamaBuffer<Fn>::flush_buffer() [with Fn = FastLlama::generate(std::function<void(const std::__cxx11::basic_string<char>&)>, std::size_t, float, float, float, std::string)::<lambda(std::string)>] » :
/home/quentin/fastLLaMa/bridge.cpp:960:28:   requis depuis ici
/home/quentin/fastLLaMa/bridge.cpp:782:37: erreur: « get_token_as_str » n'a pas été déclaré dans cette portée
  782 |         auto temp = get_token_as_str(id);
      |                     ~~~~~~~~~~~~~~~~^~~~
make[2]: *** [CMakeFiles/fastLlama.dir/build.make:76: CMakeFiles/fastLlama.dir/bridge.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/fastLlama.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
Unable to build bridge.cpp and link the 'libllama'

**Comment by Bigdimuss** [comment]
Need add 
#include <optional> on top of bridge.cpp

**Comment by poohzaza166** [comment]
so how to fix?

**Comment by poohzaza166** [comment]
> Need add #include on top of bridge.cpp

include what?

**Comment by amitsingh19975** [comment]
Add the following line at the top
```cpp
#include <optional>
```
I'll fix it in the next pull request. Somehow forgot to include it and my compiler did not complain. Thanks for reporting it.

**Comment by amitsingh19975** [comment]
check out #20

**Comment by PotatoSpudowski** [comment]
Merged. 

Closing this for now. Feel free to open it if needed!
