### ISSUE TITLE
How install on Windows?

### ISSUE THREAD

**Issue by soleimanian** [PotatoSpudowski/fastLLaMa#27]
I get the below error in windows:
ModuleNotFoundError: No module named 'fastLlama'

**Comment by amitsingh19975** [comment]
Could you explain to me the steps you took? We tested on only `Unix` based devices. To abate this kind of situation, we are thinking of consolidating make and make files into a single `CMake` file.

**Comment by stduhpf** [comment]
Are you using a code formatter? Because in my case, autopep8 likes to move the `import fastLlama` line before `sys.path.append("./build/")` for some reason, and that causes the same `ModuleNotFoundError` you are experiencing.

**Comment by amitsingh19975** [comment]
No, not at all. Are you using format on save or something on `VSCode`.

**Comment by amitsingh19975** [comment]
We updated the build system. Could you try to build it now?

**Comment by PotatoSpudowski** [comment]
Seems like the same issue as #43 

Closing this and keeping that open.
