### ISSUE TITLE
function wrap for getting the embedding

### ISSUE THREAD

**Issue by complexly** [PotatoSpudowski/fastLLaMa#36]
Thank you for this project! In the example folder of llama.cpp, there is a function to generate embedding for given text:

https://github.com/ggerganov/llama.cpp/tree/master/examples/embedding

Could you add a function wrap for this? It's great to get the embeddings locally with these language models, thanks!

**Comment by PotatoSpudowski** [comment]
Hi!

Yes definitely. I am currently in between refactoring and updating the code base to reflect the current llama.cpp codebase. Should be done in a few days!

Also structuring the repo better to allow multiple language interface support!

**Comment by AL-Kost** [comment]
Plus one to this feature request. Would be really useful :)

**Comment by PotatoSpudowski** [comment]
Done!
