### ISSUE TITLE
Still slow on AVX2 CPUs

### ISSUE THREAD

**Issue by Showdown76py** [PotatoSpudowski/fastLLaMa#37]
Hello, you recently fixed an issue concerning the incompability with AVX2 CPUs (in issue #21), but sadly it didn't seem to fix my issue.
I reset once again my VM and tried to install everything again with the latest commit of this repository, and re-installed everything, and this time I tried with the 7B model.

I can't tell if it's because it's a smaller model that what I've tried before, but it seems to be a little bit faster than before. However it is still slower than if I was using it with llama.cpp directly.

Here is a video, and in the description the different timestamps

https://youtu.be/ry8uvKAto3I
(I can't find where I can re-open this issue)

**Comment by PotatoSpudowski** [comment]
I reopened the other thread. Let us use that thread instead and understand why this is the case!
