### ISSUE TITLE
quantize.py is not build. quantize binary is.

### ISSUE THREAD

**Issue by cosimoiaia** [PotatoSpudowski/fastLLaMa#4]
The build is not generating a python file but a binary executable, which also has a different syntax.

Please clarify the Readme or change the makefile.

**Comment by PotatoSpudowski** [comment]
Hi, Nice catch. I have added the quantize.py file now :) 

Closing this issue now, Feel free to open it again if required.

**Comment by cosimoiaia** [comment]
Thank you! Great work btw :)
