### ISSUE TITLE
Passing arguments such as -ins 

### ISSUE THREAD

**Issue by regstuff** [PotatoSpudowski/fastLLaMa#41]
Hi,
Sorry if this is a stupid question, because I'm no expert at this stuff. How do I emulate the behavior of the -ins flag (and the other flags from llama.cpp) inside the python program, when I'm using alpaca models?

**Comment by PotatoSpudowski** [comment]
Hi, 
So in the example/python folder we have examples to run llama and alpaca models. 

Can you let me know what -ins mode functionality you are looking for?

**Comment by PotatoSpudowski** [comment]
Hi, 
I guess you should be able to find what you are looking for in our examples folder. 
If you still have any doubts feel free to reopen this, I will be closing this for now.
