### ISSUE TITLE
Pip support testing

### ISSUE THREAD

**Issue by PotatoSpudowski** [PotatoSpudowski/fastLLaMa#55]
Then only thing that is holding back fastLLaMa is not having pip support. 

Anyone interested in helping us out with this would be really appreciated, @amitsingh19975 and myself are busy with experimentations and maintenance of the core library. As we do not work full time on this, we would appreciate additional support! 

Thank you :)

**Comment by PotatoSpudowski** [comment]
I have added initial support for pip in `feature/pip` branch

To install fastLLaMa using pip run

```
pip install git+https://github.com/PotatoSpudowski/fastLLaMa.git@feature/pip
```

Importing should look like 

```
from fastLLaMa import Model
```

If anyone can test it out and let me know if anything is breaking, I would appreciate it!

Based on the machine you are installing, pip will install it with the appropriate flags. 
This way, I don't have to worry about managing packages for different hardware for now!

**Comment by PotatoSpudowski** [comment]
@amitsingh19975 @stduhpf Not urgent, if you guys get some time can you please test out if the pip install builds everything on your local machines? I have tested it out on Apple Silicon Mac and Intel CPU with avx2. Seems to be working as expected for me.

**Comment by vootshiclone** [comment]
```
pip install git+https://github.com/PotatoSpudowski/fastLLaMa.git@feature/pip
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/PotatoSpudowski/fastLLaMa.git@feature/pip
  Cloning https://github.com/PotatoSpudowski/fastLLaMa.git (to revision feature/pip) to /tmp/pip-req-build-5bptunmj
  Running command git clone --filter=blob:none --quiet https://github.com/PotatoSpudowski/fastLLaMa.git /tmp/pip-req-build-5bptunmj
  Running command git checkout -b feature/pip --track origin/feature/pip
  Switched to a new branch 'feature/pip'
  Branch 'feature/pip' set up to track remote branch 'feature/pip' from 'origin'.
  Resolved https://github.com/PotatoSpudowski/fastLLaMa.git to commit 768a34747213d26ea4550b4f7d9d1ebea0c88a11
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.24.2 in /usr/local/lib/python3.10/dist-packages (from fastllama==0.5) (1.24.2)
Requirement already satisfied: py-cpuinfo>=9.0.0 in /usr/local/lib/python3.10/dist-packages (from fastllama==0.5) (9.0.0)
Requirement already satisfied: inquirer>=3.1.3 in /usr/local/lib/python3.10/dist-packages (from fastllama==0.5) (3.1.3)
Requirement already satisfied: cmake>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from fastllama==0.5) (3.26.3)
Requirement already satisfied: blessed>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from inquirer>=3.1.3->fastllama==0.5) (1.20.0)
Requirement already satisfied: python-editor>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from inquirer>=3.1.3->fastllama==0.5) (1.0.4)
Requirement already satisfied: readchar>=3.0.6 in /usr/local/lib/python3.10/dist-packages (from inquirer>=3.1.3->fastllama==0.5) (4.0.5)
Requirement already satisfied: wcwidth>=0.1.4 in /usr/local/lib/python3.10/dist-packages (from blessed>=1.19.0->inquirer>=3.1.3->fastllama==0.5) (0.2.6)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from blessed>=1.19.0->inquirer>=3.1.3->fastllama==0.5) (1.16.0)
Requirement already satisfied: setuptools>=41.0 in /home/v22/.local/lib/python3.10/site-packages (from readchar>=3.0.6->inquirer>=3.1.3->fastllama==0.5) (67.7.2)
Building wheels for collected packages: fastllama
  Building wheel for fastllama (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/fastLLaMa
      copying fastLLaMa/__init__.py -> build/lib/fastLLaMa
      copying fastLLaMa/api.py -> build/lib/fastLLaMa
      /home/v22/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer, pypa/build or
              other standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      installing to build/bdist.linux-x86_64/wheel
      running install
      creating fastllama.egg-info
      writing fastllama.egg-info/PKG-INFO
      writing dependency_links to fastllama.egg-info/dependency_links.txt
      writing requirements to fastllama.egg-info/requires.txt
      writing top-level names to fastllama.egg-info/top_level.txt
      writing manifest file 'fastllama.egg-info/SOURCES.txt'
      reading manifest file 'fastllama.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file 'fastllama.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-5bptunmj/setup.py", line 55, in <module>
          setup(
        File "/home/v22/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/v22/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/v22/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/v22/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/v22/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/home/v22/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "/home/v22/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/v22/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/home/v22/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-5bptunmj/setup.py", line 28, in run
          for ext in self.extensions:
        File "/home/v22/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: extensions
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fastllama
  Running setup.py clean for fastllama
Failed to build fastllama
ERROR: Could not build wheels for fastllama, which is required to install pyproject.toml-based projects
```

**Comment by matthoffner** [comment]
Getting similar error:
```
for ext in self.extensions:
                ^^^^^^^^^^^
```

**Comment by PotatoSpudowski** [comment]
@matthoffner @vootshiclone Thank you for raising the issue.

I have updated the the setup script. Can you please try checking it now?

**Comment by matthoffner** [comment]
@PotatoSpudowski Just ran pip install on the `feature/pip` branch and confirming it installs now, thanks!

**Comment by vootshiclone** [comment]
@PotatoSpudowski successfully installed with sudo, importing doesn't work though.

**Comment by Diyago** [comment]
Failed on win10:


PS C:\Users\dex> pip install git+https://github.com/PotatoSpudowski/fastLLaMa.git@feature/pip
Collecting git+https://github.com/PotatoSpudowski/fastLLaMa.git@feature/pip
  Cloning https://github.com/PotatoSpudowski/fastLLaMa.git (to revision feature/pip) to c:\users\dex\appdata\local\temp\pip-req-build-gz4g0lcm
  Running command git clone --filter=blob:none --quiet https://github.com/PotatoSpudowski/fastLLaMa.git 'C:\Users\dex\AppData\Local\Temp\pip-req-build-gz4g0lcm'
  WARNING: Did not find branch or tag 'feature/pip', assuming revision or ref.
  Running command git checkout -q feature/pip
  error: pathspec 'feature/pip' did not match any file(s) known to git
  error: subprocess-exited-with-error

  × git checkout -q feature/pip did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q feature/pip did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by PotatoSpudowski** [comment]
@Diyago can you try using wsl? 

@vootshiclone sorry have been doing a lot of changes on that branch. we merged it to main, can you test now?

**Comment by PotatoSpudowski** [comment]
PS import is now a lil different too 

```python
from fastllama import Model
```

**Comment by vootshiclone** [comment]
@PotatoSpudowski  install worked only with this:

`sudo pip install git+https://github.com/PotatoSpudowski/fastLLaMa`

Import works👍

Trying to run the cell:

````
from fastllama import Model
MODEL_PATH = "./models/ggml-vic7b-q4_0.bin"

model = Model(
        path=MODEL_PATH, #path to model
        num_threads=14, #number of threads to use
        n_ctx=512, #context size of model
        last_n_size=64, #size of last n tokens (used for repetition penalty) (Optional)
        seed=0, #seed for random number generator (Optional)
    ) 

 ````

Here is the output:

---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
Cell In[1], line 1
----> 1 from fastllama import Model
      2 MODEL_PATH = "[./models/ggml-vic7b-q4_0.bin](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/mnt/d/Projects/chat_tg_history/fastLLaMa/models/ggml-vic7b-q4_0.bin)"
      4 model = Model(
      5         path=MODEL_PATH, #path to model
      6         num_threads=14, #number of threads to use
   (...)
      9         seed=0, #seed for random number generator (Optional)
     10     )

File /usr/local/lib/python3.10/dist-packages/fastllama/__init__.py:2
      1 import os;
----> 2 from .api import *
      4 set_library_path(os.path.dirname(os.path.abspath(__file__)))

File :1027, in _find_and_load(name, import_)

File :1006, in _find_and_load_unlocked(name, import_)

File :688, in _load_unlocked(spec)

File :879, in exec_module(self, module)

File :1016, in get_code(self, fullname)

File :1073, in get_data(self, path)

PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/fastllama/api.py'

**Comment by amitsingh19975** [comment]
> @PotatoSpudowski install worked only with this:
> 
> `sudo pip install git+https://github.com/PotatoSpudowski/fastLLaMa`
> 
> Import works👍
> 
> Trying to run the cell:
> 
> ```
> from fastllama import Model
> MODEL_PATH = "./models/ggml-vic7b-q4_0.bin"
> 
> model = Model(
>         path=MODEL_PATH, #path to model
>         num_threads=14, #number of threads to use
>         n_ctx=512, #context size of model
>         last_n_size=64, #size of last n tokens (used for repetition penalty) (Optional)
>         seed=0, #seed for random number generator (Optional)
>     ) 
> ```
> 
> Here is the output:
> 
> PermissionError Traceback (most recent call last) Cell In[1], line 1 ----> 1 from fastllama import Model 2 MODEL_PATH = "[./models/ggml-vic7b-q4_0.bin](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/mnt/d/Projects/chat_tg_history/fastLLaMa/models/ggml-vic7b-q4_0.bin)" 4 model = Model( 5 path=MODEL_PATH, #path to model 6 num_threads=14, #number of threads to use (...) 9 seed=0, #seed for random number generator (Optional) 10 )
> 
> File /usr/local/lib/python3.10/dist-packages/fastllama/**init**.py:2 1 import os; ----> 2 from .api import * 4 set_library_path(os.path.dirname(os.path.abspath(**file**)))
> 
> File :1027, in _find_and_load(name, import_)
> 
> File :1006, in _find_and_load_unlocked(name, import_)
> 
> File :688, in _load_unlocked(spec)
> 
> File :879, in exec_module(self, module)
> 
> File :1016, in get_code(self, fullname)
> 
> File :1073, in get_data(self, path)
> 
> PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/fastllama/api.py'

You're installing the package as a superuser. Therefore, you have to run the program as a superuser. If you want to run the program normally, I would suggest installing it as a normal user.

**Comment by vootshiclone** [comment]
@amitsingh19975 I'm a noob.

![image](https://user-images.githubusercontent.com/66087221/235514637-5540c1ca-acc6-40f5-bc7c-b157199246bd.png)

How do I run it with superuser?

**Comment by amitsingh19975** [comment]
just add sudo before the command

```sh
sudo python example.py
```

**Comment by vootshiclone** [comment]
@amitsingh19975 Yep, nevermind, works as expected with sudo 👍

**Comment by PotatoSpudowski** [comment]
Coolio, I guess we can close this issue in 2 days. 

If any one faces any issues feel free to add it here or reopen if it has been closed

**Comment by vootshiclone** [comment]
@PotatoSpudowski Don't want to be a drag, but here is the dilema:

In order to use it in jupiter I need to run it NOT as a superuser (running cells as superuser in jupiter is painfull). I think a lot of people out there would prefer to use it that way.  So to do that I have to stick with the old installation way (please, put it back to README for people like me) and `from interfaces.python.fastllama import Model` as a way of importing it.

On the other hand it would be cool to install it with pip withut sudo as a normal user (and without the need to manually add it to PATH).

**Comment by amitsingh19975** [comment]
I'm assuming you're new to Unix based os, but it's not a issue on our side. You have install python as normal user then you wouldn't face problem. Once you install anything in Unix based system the only way to run executable is running them as superuser. 

There are a few ways to fix that if you're not keen on installing python again:
1. Changing the permissions for user using `chmod`
2. Put the session in superuser mode using `sudo su` if my serves me right.

However, I would say fix you're python installation because it'll save your time in future.

**Comment by stduhpf** [comment]
Ah, I found the issue, deleting directory `examples/python/fastllama/`made it work.
