### ISSUE TITLE
    from build.fastllama import Model, ModelKind ModuleNotFoundError: No module named 'build.fastllama'

### ISSUE THREAD

**Issue by lucasjinreal** [PotatoSpudowski/fastLLaMa#56]
from build.fastllama import Model, ModelKind
ModuleNotFoundError: No module named 'build.fastllama'

**Comment by PotatoSpudowski** [comment]
There are two reasons this can be caused:
1. not compiling with `python setup.py -l python`
2. not running your examples from root dir.

If it's the latter, It is because we are using relative paths right now. We will fix it in the near future.

**Comment by lucasjinreal** [comment]
@PotatoSpudowski hello, I have runed setup,op -l python
and I am in root dir. macOS got this issue

**Comment by amitsingh19975** [comment]
If you are still having this issue, I can suggest you use `sys.path.append` to append the path to the `fastllama.py` inside the build directory. And change the import according to that.

**Comment by PotatoSpudowski** [comment]
Did this get resolved? @lucasjinreal

**Comment by leedrake5** [comment]
> If you are still having this issue, I can suggest you use `sys.path.append` to append the path to the `fastllama.py` inside the build directory. And change the import according to that.

The problem seems to be that fastllama.py is located in interfaces/python/, not build/interfaces/python. Not sure that setup.py is setting up correctly.

**Comment by leedrake5** [comment]
Follow up, manually copying fastllama.py to build/interfaces/python AND copying pyfastllama.so from build/interfaces/python to build makes the app functional on Macs. Hopefully setup.py can be tweaked so the simple install works.

**Comment by PotatoSpudowski** [comment]
Yup, in this [branch](https://github.com/PotatoSpudowski/fastLLaMa/tree/feature/pip) we are trying to make it more simplified.

**Comment by PotatoSpudowski** [comment]
Absolute paths have been removed in the new commit. Can close this for now.
