### ISSUE TITLE
When stop words are reached, they get ingested, but are not forwarded to streaming_fn.

### ISSUE THREAD

**Issue by stduhpf** [PotatoSpudowski/fastLLaMa#62]
This is an issue, because when I try to run something like this:
```python
from build.fastllama import Model, ModelKind

MODEL_PATH = "./models/ALPACA-LORA-7B/alpaca-lora-q4_0.bin"

def stream_token(x: str) -> None:
    """
    This function is called by the llama library to stream tokens
    """
    print(x, end='', flush=True)

model = Model(
        id=ModelKind.ALPACA_LORA_7B,
        path=MODEL_PATH, #path to model
        num_threads=16, #number of threads to use
        n_ctx=512, #context size of model
        last_n_size=16, #size of last n tokens (used for repetition penalty) (Optional)
        n_batch=128,
    )
prompt = """A: I am A, Hello
B: I am B, Hello A
B: I am B, How are you?
A: I am A, I'm fine, what about you?"""

print(prompt,end='')
res = model.ingest(prompt)
while True:

    res = model.generate(
        num_tokens=512, 
        top_p=0.95, #top p sampling (Optional)
        temp=0.8, #temperature (Optional)
        repeat_penalty=1.0, #repetition penalty (Optional)
        streaming_fn=stream_token, #streaming function
        stop_words=["\nB: "] #stop generation when this word is encountered (Optional)
        )

    print("\n###")
```

The output looks like that: 
```
A: I am A, Hello
B: I am B, Hello A
B: I am B, How are you?
A: I am A, I'm fine, what about you?
###
 am B, I'm good. How is your day going?
A: I am A, It's going well.
###
 am B, Nice to hear.
A: I am A, What do you do?
###
 am B, I'm a web developer.
A: I am A, That's cool.
###
 am B, Thanks.
A: I am A, It's been a pleasure chatting with you.
###
 am B, See you soon.
A: I am A, Bye!
```
As you can see, the stop word is supposed to be "\nB: ", but probably beacuse of some quirk of the tokenizer, it seems like the model actually generates and ingests "\nB: I" everytime. Because it contains the stop word, the models stop generating, but still has the "I" already ingested. 
When that happens in an interactive chatbot-like setup, it could degrade the quality of the result.

I can think of two potential improvements regarding this issue:
- Always send the generated tokens to the streaming funnction, even if the stop word is reached
- If a stop word is detecteed, replace the generated token by the actual stop word token, to avoid cases where extra text is generated but not displayed.

**Comment by PotatoSpudowski** [comment]
@stduhpf this is a very nice insight!
Thank you for your efforts wrt identifying issues such as this. Really appreciate it!

I will have a look at this!

**Comment by stduhpf** [comment]
It's working as expected now, thank you!
The only annoyance remaining is that there is no way to know which stop word gets generated in case of multiple stop words.

**Comment by PotatoSpudowski** [comment]
Good feature to implement next!
