### ISSUE TITLE
Example doc has incorrect repo

### ISSUE THREAD

**Issue by raldebsi** [PotatoSpudowski/fastLLaMa#7]
Hi,
I noticed in your readme the repo is `fast_llama` instead of `fastLLaMa`. Not worth making a PR for it so I thought of giving a heads up!

- Thx for repo

**Comment by PotatoSpudowski** [comment]
Hi you're right. I thought of calling it fast_llama first then I changed my mind xD

Will fix it. Glad you liked the work :)
